#!/bin/sh

# check if this is run at the root of the project
if [ ! -d "src" ]; then
    echo "This script must be run at the root of the project"
    exit 1
fi

DIR="src"
EXCLUDE_DIR="3rdparty"

find "$DIR" -path "*/$EXCLUDE_DIR/*" -prune -o \( -name "*.cpp" -o -name "*.hpp" -o -name "*.h" -o -name "*.inl" \) -print | xargs clang-format -i
